# Generated by Django 5.0.6 on 2024-06-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_table',
            name='name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
