# Generated by Django 5.0.6 on 2024-06-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_test_table_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test_table',
        ),
    ]
